name: API CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  testing:
    runs-on: ubuntu-latest
    env:
      GO_VERSION: 1.16
    
    steps:

      - uses:  actions/checkout@v3

      - name: Set up Go ${{ env.GO_VERSION }} 
        uses: actions/checkout@v3  #git clone into runner
        with:
          go-version: ${{ env.GO_VERSION }} 
        
      - name: Setup Node.js
        uses: actions/setup-node@v4 # instalar node 
        with: 
          node-version: 20.x

      - name: Install Dependencies # instalar las dependencias
        run: go mod download

      - name: Test
        run: go test -v ./...

      - name: Run build
        run: go build -v ./...

      - name: CI Successful Ok
        if: success()
        uses: rtCamp/action-slack-notify@v2
        with:
          status: 'passed'
          text: 'Go CI succesfully.'
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      #- name: Run code linter
      #- run: npm run lint
