name: API CI
ins
on:
   push:
    branches: [main, develop]
  pull_request:
      branches: [main, develop]

jobs:
  testing:
      runs-on: ubuntu-latest
      env:
        GO_VERSION: 1.16

      steps: 
          - name: Checkout repo 
          - uses: action/checkout@v4  #PARA CLONAR, GIT CLONE 
        
          - name: Setup Go ${( env.GO_VERSION )}
            uses: action/setup-node@v4 # CON ESTO INSTALAMOS NODE 
              with: 
                  go-version: ${( env.GO_VERSION )}

          - name: Install Dependencies # INSTALAMOS NUESTRA DEPENDENCIAS
          - run: go mod download

          - name: Run unit and integrate tests # PODEMOS EJECUTAR NUESTRAS TAREAS
          - run: go test -v

          - name: Run build # NOS AYUDA EN LA COMPILACION Y EN LA ENSAMBLACION DECODIGO
          - run: go build -v

          - name: CI Succesful OK
            if: success()
            uses: rtCamp/action-slack-notify@v2
            with:
              status: 'passed'
              text: 'Go CI succesfully.'
            env:
              SLACK_WEBHOOK: ${( secrect.SLACK_WEBHOOK )}

          #- name: Run code linter
          #- run: npm run lint